### ISSUE TITLE
push tags for each release

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#197]
it would be nice to have tags every time we make a new release

for now we only have a 0.1.0 tag even though there's been a lot of other more recent releases

**Comment by kontur** [comment]
Adding `gftools` to the build requirements for [Signika](https://github.com/Ancymonic/Signika) I would like to reference the current release, so this would be useful indeed. Now I'm referencing the latest commit to specify a reproducible dependency tree.

**Comment by alerque** [comment]
Yes please. I'm having trouble debugging `gftools` issues because the Pypi releases are not correlated with git tags, so checking the logs and bisecting to figure out what changed / broke my font builds is very tedious and manual. Please add git tags for each version bump at the commit that was used to push Pypi releases.

**Comment by m4rc1e** [comment]
@alerque Please could you open an issue? Just dump the traceback and I'll get back to you asap.

**Comment by m4rc1e** [comment]
Added in #265.
