### ISSUE TITLE
add -o --out to fix scripts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#243]
We have many fix scripts which don't allow users to specify an output path. Most fix scripts will output a fixed font with `.fix` appended to the input font path. Adding an optional `-o/--out` arg would be a nice touch.

**Comment by m4rc1e** [comment]
If we do implement this, we must add this feature so it doesn't break existing projects.

**Comment by alerque** [comment]
This would be an awesome thing to have a proper fix for! I've seen hundreds of (frequently dirty) shell scripts working around this irregularity.

Orthogonality related because it causes the same genre of problem while trying to automate build pipelines: https://github.com/googlefonts/fontmake/issues/693

**Comment by simoncozens** [comment]
This is something we still need to do, but it's essentially the same issue as #136.
