### ISSUE TITLE
filter_lists.py should use pkg_resources to manage XML data files from GlyphsInfo

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#31]
`bin/gftools-namelist.py` does `from gftools.util  import filter_lists` which relies on an XML file which is read via opening a filepath defined directly with `FILE_DIR = os.path.dirname(os.path.realpath(__file__))` on `Lib/gftools/util/glyphdata.py`.

When packaging, the XML file won't be found and the code won't work. This code should be updated to use `pgk_resources`. But this code is in another git repo which is loaded as a git submodule here.

**Comment by felipesanches** [comment]
I had not noticed this because I was running "pip install -e ." and then the script was wable to find the XML file in the git repo. But by creating a new virtualenv and doing "pip install ." I can replicate what a user would get in a non-development environment. And as expected, the code crashes, being unable to find the XML file.

**Comment by felipesanches** [comment]
Actually, filter_lists.py is in this repo, so I can fix it. Sorry about the confusion, @anthrotype

**Comment by anthrotype** [comment]
before you build the distribution packges (sdist and wheel) for this project, you have to make sure that the submodules are cloned and checked-out, so that the required data files are present in the sub-directory.

Then you have to add the data files you wish to include to the `MANIFEST.in` file and set `include_package_data=True` in `setup.py` (check setuptools docs or see how other projects do).

http://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

Then from the python script that needs to load the data file, you can use `pkg_resources.resource_filename` instead of relying on `__file__` (which is not always there, .e.g. in a zip file)
http://setuptools.readthedocs.io/en/latest/pkg_resources.html#resource-extraction

**Comment by felipesanches** [comment]
yeah, I've just done something similar for the Vendor ID cache file on fontbakery:
https://github.com/googlefonts/fontbakery/commit/8be20147f2cf3bb7d28641fad487ec9b6aec5d2c

What's the benefit of the MANIFEST.in approach versus package_data on setup.py ?

**Comment by anthrotype** [comment]
both are fine. whatever works for you.

**Comment by felipesanches** [comment]
cool, thanks for the tips!

**Comment by simoncozens** [comment]
We now use the GlyphsInfo submodule to load these files, and `MANIFEST.in` to include them in the distribution.
