### ISSUE TITLE
Builder: Add docs

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#344]
gftools builder should have docs which are hosted in our [docs/](https://github.com/googlefonts/gftools/tree/main/docs) dir. Most designers don't open source code. Simplest solution is to just use the builder's doc string.

**Comment by RosaWagner** [comment]
This repo can be used as an example in the doc : https://github.com/Omnibus-Type/Texturina/blob/master/sources/config.yaml

it shows the builder with a case of:
- Roman + Italic
- Multi axes (weight, optical size, italique)
- custom stat (because the axis registry for opsz axis has too much fallbacks)
