### ISSUE TITLE
Making Vietnamese look better: What command? :)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#35]
@alexeiva in https://github.com/googlefonts/tools/blob/3c49ede147bc8aa2bccfebb2b2d700e1accf2b6c/encodings/GF%20Glyph%20Sets/Vietnamese/README.md you wrote,

> Then, the following command will create new unique Vietnamese glyphs with special accents, and generate additional localized variants for these glyphs:

What is the following command, though? What follows is just a list of glyph names 

cc @EbenSorkin @crystaltype

**Comment by davelab6** [comment]
@alexeiva and, does this technique mean that there are 2 versions of Vietnamese, one which uses the special localized version (when `locl` is processed, such as when `<html lang="vn">` or whatever it is) and one which does not (when `locl` is not processed, such as `<html>`)

**Comment by alexeiva** [comment]
<img width="485" alt="screen shot 2017-11-27 at 11 59 04 pm" src="https://user-images.githubusercontent.com/16634089/33286518-fec84e36-d3ce-11e7-84a7-5292a3fdc000.png">

```
acutecomb = acutecomb.loclVIT
gravecomb = gravecomb.loclVIT
...
```

This is called a glyphs command because it generates glyph `acutecomb.loclVIT` and places `acutecomb` as a component in the new glyph.


> does this technique mean that there are 2 versions of Vietnamese

Yes, two versions in the manner you described. This is a compromise solution initially suggested for Libre Franklin, where Pablo didn't what changes in the common Latin glyphs, while Nhung insisted on special Vietnamese variants.

**Comment by EbenSorkin** [comment]
So the issues was common latin base glyphs like 'u' or 'a' or 'A' - correct?

If so then the reason we were asking was different. The reason Dave and I
were asking is that I was saying that the standard unicode spots for
Vietnamese language glyphs like 'acircumflexhookabove' uniIEA9 should not
use all component diacritics above the base glyphs but instead use one
precomposed diacritic. e.g rather thant having "brevecomb_gravecomb"
uni03060300
be made from the components brevecomb and gravecomb at full size these
components would be decomposed and scaled and the adjusted appropriately to
give a more more consistent optical weight with other single diacritics.

I attach an example where this adjustment has been done. At the moment I
regard this kind of scaling as being best design practice. Do you agree?

Dave, I have been thinking of asking Rainer/Glyphs to update what they do
automatically because it seems to superficially encourage a sub-optimal
solution. I was thinking of cc:ing them on this. Do you mind if I do that?

-e.

**Comment by davelab6** [comment]
Github doesn't accept email attachments, please go to this issue page and edit your comment and drag and drop in the image

**Comment by davelab6** [comment]
Oh I see, so, the user reruns the Add Glyphs command

**Comment by EbenSorkin** [comment]
![vientdiacriticexample](https://user-images.githubusercontent.com/2181213/33331425-8e43f190-d42f-11e7-879b-66b31e133a0f.png)

**Comment by EbenSorkin** [comment]
Also thanks for the heads up Dave!

**Comment by alexeiva** [comment]
@EbenSorkin That's exactly the way it is made in Glyphs App.

For example, Nunito Sans:
<img width="638" alt="screen shot 2017-12-04 at 4 11 34 pm" src="https://user-images.githubusercontent.com/16634089/33552291-e71d4f40-d90d-11e7-90ac-5105110fa0d7.png">

Under Latin > Vietnamese tab there is a set of precomposed stacked accents. 
To make ắ `abreveacute` Glyphs combines `a` + `brevecomb_acutecomb`




<img width="971" alt="screen shot 2017-12-04 at 4 10 03 pm" src="https://user-images.githubusercontent.com/16634089/33552301-f0ae3268-d90d-11e7-9ca6-178f5695a5ae.png">

**Comment by EbenSorkin** [comment]
Are you saying that Glyphs provides ( or can be made to provide)  the
unique unicodes codepoints for Vietnamese?

That's the best interpretation I can put to your post. Did I get it right?

Just my two cents the breve in the example on the far right looks a bit to
deemphasized to me. I think the acute could be a bit less long instead
maybe. Also assuming the scheme for vertical metrics works well might the
vietnamese diacritic be slightly taller as well? Maybe this was designed
before that scheme was invented.

-e.

**Comment by alexeiva** [comment]
> Are you saying that Glyphs provides ( or can be made to provide)  the
> unique unicodes codepoints for Vietnamese?

No, these are unencoded glyphs by default

They can be made to have unicode points if you edit [GlyphsData.xml](https://glyphsapp.com/tutorials/roll-your-own-glyph-data)

If these changes are added to the [master GlyphsData](https://raw.githubusercontent.com/schriftgestalt/GlyphsInfo/master/GlyphData.xml) file, they will be accessible to everyone in the next update.

What are the codepoints? I can update the file if you tell me.

**Comment by simoncozens** [comment]
I'm not convinced this is actually a gftools issue. But reopen if so!...
