### ISSUE TITLE
Font names are getting ridiculous: "SixtyfourRegularRegularRegular-Regular"

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/gftools#388]
I have built [those fonts](https://github.com/jenskutilek/homecomputer-fonts) with `gftools builder` and some font names are a bit ridiculous.

```xml
    <namerecord nameID="263" platformID="3" platEncID="1" langID="0x409">
      SixtyfourRegularRegularRegular-Regular
    </namerecord>
```

The font has 2 axes (BLED, SCAN), 3 in the STAT table (BLED, SCAN, ital), I guess all the names of each axis’ default location get appended even though all but one are marked as elidable.

**Comment by m4rc1e** [comment]
You are correct that all name tokens are appended even if they are elided for the ps fvar instance names. I did this because you could end up in a situation where two instances have the same postscript name. This will only occur if a STAT Axis Record has two AxisValues which are elided. In theory one would expect there to only be one elided AxisValue for each Axis Record but you're free to have as many as you want.

afaik, ps fvar instance names are not visible in any application.

I was against adding fvar ps instance names due to lock in but apparently they were needed in order to get Indesign to work. Going forward, I'm never going to add any superfluous features just to get something to work in an incorrect software implementation.

**Comment by thlinard** [comment]
> I was against adding fvar ps instance names due to lock in but apparently they were needed in order to get Indesign to work. Going forward, I'm never going to add any superfluous features just to get something to work in an incorrect software implementation. I will adhere to the spec and not requirements which could change overnight.

I would say gftools should never produce anything contrary to the specs, but if a non-mandatory feature exists in the specs, it should be able to be produced on demand.

**Comment by m4rc1e** [comment]
@thlinard I don't really care about your opinions on this issue going forward so I wouldn't bother wasting your time replying. I should've stuck to my initial thoughts and ignored your request to add the ps names just so we could support a now outdated version indesign. The correct solution for these issues going forward is to work with the software vendors so that their implementations will work correctly without us adding unnecessary features or hacks to our fonts.

**Comment by thlinard** [comment]
> @thlinard I don't really care about your opinions on this issue going forward so I wouldn't bother wasting your time replying.

Ouch! That was rude and undeserved, but I got the message. As for me, I'll remain favorably disposed to your requests, as I have been in the past.
