### ISSUE TITLE
duplicate scripts? 

### ISSUE THREAD

**Issue by devosb** [googlefonts/gftools#847]
Two scripts seem to be almost duplicates of each other. Both `fix-family` and `fix-font` has the same options for changing fonts 

- `--include-source-fixes`
- `--rename-family`
- `--fvar-instance-axis-dflts`

But the file handling is different, `fix-family` but not `fix-font`, supports

- `--inplace`
- multiple input fonts
- the `--out` option is for a directory, rather than (I think) a path to the output font file

**Comment by simoncozens** [comment]
These are very similar, but they're different and I think they should stay. `fix-family` is intended for fixing multiple fonts in the same family -which is why it outputs multiple fonts to a directory not to a single output file it considers the family as a whole i.e. ensuring the names are consistent across the family.
