### ISSUE TITLE
[Builder] how to prevent SC families to build

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#958]
I would like to not export SC families by default, but can't find the entry to add in the config.yaml. This is what --help gives me:

```
gftools builder --help
usage: gftools [-h] [--graph] [--no-ninja] [--generate] config [config ...]

positional arguments:
  config      Path to config file or source file

options:
  -h, --help  show this help message and exit
  --graph     Draw a graph of the build process
  --no-ninja  Do not run ninja
  --generate  Just generate and output recipe from recipe builder
```

**Comment by simoncozens** [comment]
The quick answer is `buildSmallCap: false`, I will add it to the documentation. Because the builder can be used to support multiple different build configurations (googlefonts is only one of them), we don't put the options in the --help any more, but most of the options are in the [README](https://github.com/googlefonts/gftools/blob/builder2/docs/gftools-builder/README.md).

**Comment by RosaWagner** [comment]
Ok thanks :)

**Comment by RosaWagner** [comment]
Sorry re-opening, the `buildSmallCap: false` is creating a Invalid configuration file error

**Comment by simoncozens** [comment]
Urgh, I didn't put it in the schema. Fixing now.
